<?xml version="1.0" encoding="UTF-8"?>
<tileset name="tileset" tilewidth="16" tileheight="16" tilecount="1160" columns="58">
 <image source="tileset.png" width="928" height="320"/>
 <tile id="118" type="floor"/>
 <tile id="119" type="floor"/>
 <tile id="120" type="floor"/>
 <tile id="121" type="floor"/>
 <tile id="122" type="floor"/>
 <tile id="123" type="floor"/>
 <tile id="124" type="floor"/>
 <tile id="194" type="floor"/>
 <tile id="195" type="floor"/>
 <tile id="196" type="floor"/>
 <tile id="197" type="floor"/>
 <tile id="199" type="floor"/>
 <tile id="201" type="floor"/>
 <tile id="202" type="floor"/>
 <tile id="203" type="floor"/>
 <tile id="204" type="floor"/>
 <tile id="265" type="floor"/>
 <tile id="266" type="floor"/>
 <tile id="267" type="floor"/>
 <tile id="269" type="floor"/>
 <tile id="270" type="floor"/>
 <tile id="271" type="floor"/>
 <tile id="272" type="floor"/>
 <tile id="467" type="floor"/>
 <tile id="468" type="floor"/>
 <tile id="469" type="floor"/>
 <tile id="473" type="floor"/>
 <tile id="474" type="floor"/>
 <tile id="698" type="floor"/>
 <tile id="699" type="floor"/>
 <tile id="700" type="floor"/>
 <tile id="701" type="floor"/>
 <tile id="702" type="floor"/>
 <tile id="703" type="floor"/>
 <tile id="705" type="floor"/>
 <tile id="706" type="floor"/>
 <tile id="708" type="floor"/>
 <tile id="709" type="floor"/>
 <tile id="710" type="floor"/>
 <tile id="712" type="floor"/>
 <tile id="713" type="floor"/>
 <tile id="715" type="floor"/>
 <tile id="716" type="floor"/>
 <tile id="718" type="floor"/>
 <tile id="720" type="floor"/>
 <tile id="721" type="floor"/>
 <tile id="723" type="floor"/>
 <tile id="724" type="floor"/>
 <tile id="726" type="floor"/>
 <tile id="728" type="floor"/>
 <tile id="729" type="floor"/>
 <tile id="730" type="floor"/>
 <tile id="733" type="floor"/>
 <tile id="734" type="floor"/>
 <tile id="736" type="floor"/>
 <tile id="737" type="floor"/>
 <tile id="739" type="floor"/>
 <tile id="740" type="floor"/>
 <tile id="908" type="floor"/>
 <tile id="909" type="floor"/>
 <tile id="911" type="floor"/>
 <tile id="957" type="floor"/>
 <tile id="958" type="floor"/>
 <tile id="965" type="floor"/>
 <tile id="966" type="floor"/>
 <tile id="967" type="floor"/>
 <tile id="969" type="floor"/>
 <tile id="970" type="floor"/>
 <tile id="1022" type="floor"/>
 <tile id="1023" type="floor"/>
 <tile id="1024" type="floor"/>
 <tile id="1028" type="floor"/>
 <tile id="1029" type="floor"/>
</tileset>
