<?xml version="1.0" encoding="UTF-8"?>
<tileset name="tileset" tilewidth="16" tileheight="16" tilecount="1160" columns="58">
 <image source="tileset.png" width="928" height="320"/>
 <tile id="118" type="floor"/>
 <tile id="119" type="floor"/>
 <tile id="120" type="floor"/>
 <tile id="121" type="floor"/>
 <tile id="122" type="floor"/>
 <tile id="123" type="floor"/>
 <tile id="124" type="floor"/>
 <tile id="141" type="floor"/>
 <tile id="143" type="floor"/>
 <tile id="144" type="floor"/>
 <tile id="145" type="floor"/>
 <tile id="207" type="floor"/>
 <tile id="208" type="floor"/>
 <tile id="209" type="floor"/>
 <tile id="211" type="floor"/>
 <tile id="212" type="floor"/>
 <tile id="213" type="floor"/>
 <tile id="214" type="floor"/>
 <tile id="473" type="floor"/>
 <tile id="474" type="floor"/>
 <tile id="675" type="floor"/>
 <tile id="676" type="floor"/>
 <tile id="678" type="floor"/>
 <tile id="679" type="floor"/>
 <tile id="681" type="floor"/>
 <tile id="682" type="floor"/>
 <tile id="698" type="floor"/>
 <tile id="699" type="floor"/>
 <tile id="700" type="floor"/>
 <tile id="701" type="floor"/>
 <tile id="702" type="floor"/>
 <tile id="703" type="floor"/>
 <tile id="705" type="floor"/>
 <tile id="706" type="floor"/>
 <tile id="708" type="floor"/>
 <tile id="709" type="floor"/>
 <tile id="710" type="floor"/>
 <tile id="712" type="floor"/>
 <tile id="713" type="floor"/>
 <tile id="715" type="floor"/>
 <tile id="716" type="floor"/>
 <tile id="718" type="floor"/>
 <tile id="720" type="floor"/>
 <tile id="721" type="floor"/>
 <tile id="723" type="floor"/>
 <tile id="724" type="floor"/>
 <tile id="726" type="floor"/>
 <tile id="728" type="floor"/>
 <tile id="729" type="floor"/>
 <tile id="730" type="floor"/>
 <tile id="957" type="floor"/>
 <tile id="958" type="floor"/>
</tileset>
